apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: legacy-billing-api
  annotations:
    github.com/project-slug: dcohen213/legacy-billing-api
spec:
  type: other
  lifecycle: unknown
  owner: rhdh-team
